/*
 * The Blue Alliance API v3
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events. If you are looking for the old version (v2) of the API, documentation can be found [here](/apidocs/v2).   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.thefletcher.tbaapi.v3client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import net.thefletcher.tbaapi.v3client.model.EventInsights2017Detail;

/**
 * Insights for FIRST STEAMWORKS qualification and elimination matches.
 */
@ApiModel(description = "Insights for FIRST STEAMWORKS qualification and elimination matches.")

public class EventInsights2017 {
  @SerializedName("qual")
  private EventInsights2017Detail qual = null;

  @SerializedName("playoff")
  private EventInsights2017Detail playoff = null;

  public EventInsights2017 qual(EventInsights2017Detail qual) {
    this.qual = qual;
    return this;
  }

   /**
   * Get qual
   * @return qual
  **/
  @ApiModelProperty(value = "")
  public EventInsights2017Detail getQual() {
    return qual;
  }

  public void setQual(EventInsights2017Detail qual) {
    this.qual = qual;
  }

  public EventInsights2017 playoff(EventInsights2017Detail playoff) {
    this.playoff = playoff;
    return this;
  }

   /**
   * Get playoff
   * @return playoff
  **/
  @ApiModelProperty(value = "")
  public EventInsights2017Detail getPlayoff() {
    return playoff;
  }

  public void setPlayoff(EventInsights2017Detail playoff) {
    this.playoff = playoff;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventInsights2017 eventInsights2017 = (EventInsights2017) o;
    return Objects.equals(this.qual, eventInsights2017.qual) &&
        Objects.equals(this.playoff, eventInsights2017.playoff);
  }

  @Override
  public int hashCode() {
    return Objects.hash(qual, playoff);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventInsights2017 {\n");
    
    sb.append("    qual: ").append(toIndentedString(qual)).append("\n");
    sb.append("    playoff: ").append(toIndentedString(playoff)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

